### ISSUE TITLE
Did this ever get worked on?

### ISSUE THREAD

**Issue by kuza55** [SANSA-Stack/Spark-Tensors#1]
Hey,

I'm interested in trying some of these algorithms on my data; did you ever get around to working on these?

**Comment by ana0516392** [comment]
is the pom file working fine ?

**Comment by JensLehmann** [comment]
This repository is temporary - the code will soon be integrated into https://github.com/SANSA-Stack/SANSA-RDF and https://github.com/SANSA-Stack/SANSA-ML and you can then run the algorithms.

**Comment by JensLehmann** [comment]
Issue closed since the code is now in SANSA-RDF and SANSA-ML as mentioned above.
